import './globals.css'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    {/* <head>
      <div style={{backgroundColor:'#FFF',width:'100%',height:'53px'}}>
        Hi
      </div>
    </head> */}
    
      <head></head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
